// Domicile options for Indonesia
export const DOMICILE_OPTIONS = [
  // Aceh
  { value: "aceh-barat", label: "Kabupaten Aceh Barat - Aceh" },
  { value: "aceh-besar", label: "Kabupaten Aceh Besar - Aceh" },
  { value: "aceh-selatan", label: "Kabupaten Aceh Selatan - Aceh" },
  { value: "aceh-utara", label: "Kabupaten Aceh Utara - Aceh" },
  { value: "aceh-tengah", label: "Kabupaten Aceh Tengah - Aceh" },
  { value: "aceh-tenggara", label: "Kabupaten Aceh Tenggara - Aceh" },
  { value: "nagan-raya", label: "Kabupaten Nagan Raya - Aceh" },
  { value: "aceh-jaya", label: "Kabupaten Aceh Jaya - Aceh" },
  { value: "simeulue", label: "Kabupaten Simeulue - Aceh" },
  { value: "banda-aceh", label: "Kota Banda Aceh - Aceh" },
  { value: "sabang", label: "Kota Sabang - Aceh" },
  { value: "lhokseumawe", label: "Kota Lhokseumawe - Aceh" },
  { value: "langsa", label: "Kota Langsa - Aceh" },

  // DKI Jakarta
  { value: "jakarta-barat", label: "Kota Jakarta Barat - DKI Jakarta" },
  { value: "jakarta-pusat", label: "Kota Jakarta Pusat - DKI Jakarta" },
  { value: "jakarta-selatan", label: "Kota Jakarta Selatan - DKI Jakarta" },
  { value: "jakarta-timur", label: "Kota Jakarta Timur - DKI Jakarta" },
  { value: "jakarta-utara", label: "Kota Jakarta Utara - DKI Jakarta" },
  { value: "kepulauan-seribu", label: "Kabupaten Kepulauan Seribu - DKI Jakarta" },

  // Jawa Barat
  { value: "bandung", label: "Kota Bandung - Jawa Barat" },
  { value: "bandung-barat", label: "Kabupaten Bandung Barat - Jawa Barat" },
  { value: "bekasi", label: "Kota Bekasi - Jawa Barat" },
  { value: "bekasi-kab", label: "Kabupaten Bekasi - Jawa Barat" },
  { value: "bogor", label: "Kota Bogor - Jawa Barat" },
  { value: "bogor-kab", label: "Kabupaten Bogor - Jawa Barat" },
  { value: "cirebon", label: "Kota Cirebon - Jawa Barat" },
  { value: "cirebon-kab", label: "Kabupaten Cirebon - Jawa Barat" },
  { value: "depok", label: "Kota Depok - Jawa Barat" },
  { value: "sukabumi", label: "Kota Sukabumi - Jawa Barat" },
  { value: "sukabumi-kab", label: "Kabupaten Sukabumi - Jawa Barat" },
  { value: "tasikmalaya", label: "Kota Tasikmalaya - Jawa Barat" },
  { value: "tasikmalaya-kab", label: "Kabupaten Tasikmalaya - Jawa Barat" },
  { value: "banjar", label: "Kota Banjar - Jawa Barat" },
  { value: "cianjur", label: "Kabupaten Cianjur - Jawa Barat" },
  { value: "garut", label: "Kabupaten Garut - Jawa Barat" },
  { value: "indramayu", label: "Kabupaten Indramayu - Jawa Barat" },
  { value: "karawang", label: "Kabupaten Karawang - Jawa Barat" },
  { value: "kuningan", label: "Kabupaten Kuningan - Jawa Barat" },
  { value: "majalengka", label: "Kabupaten Majalengka - Jawa Barat" },
  { value: "purwakarta", label: "Kabupaten Purwakarta - Jawa Barat" },
  { value: "subang", label: "Kabupaten Subang - Jawa Barat" },
  { value: "sumedang", label: "Kabupaten Sumedang - Jawa Barat" },

  // Jawa Tengah
  { value: "semarang", label: "Kota Semarang - Jawa Tengah" },
  { value: "semarang-kab", label: "Kabupaten Semarang - Jawa Tengah" },
  { value: "pekalongan", label: "Kota Pekalongan - Jawa Tengah" },
  { value: "pekalongan-kab", label: "Kabupaten Pekalongan - Jawa Tengah" },
  { value: "salatiga", label: "Kota Salatiga - Jawa Tengah" },
  { value: "tegal", label: "Kota Tegal - Jawa Tengah" },
  { value: "tegal-kab", label: "Kabupaten Tegal - Jawa Tengah" },
  { value: "surakarta", label: "Kota Surakarta - Jawa Tengah" },
  { value: "magelang", label: "Kota Magelang - Jawa Tengah" },
  { value: "magelang-kab", label: "Kabupaten Magelang - Jawa Tengah" },
  { value: "ambarawa", label: "Kota Ambarawa - Jawa Tengah" },
  { value: "batang", label: "Kabupaten Batang - Jawa Tengah" },
  { value: "blora", label: "Kabupaten Blora - Jawa Tengah" },
  { value: "boyolali", label: "Kabupaten Boyolali - Jawa Tengah" },
  { value: "demak", label: "Kabupaten Demak - Jawa Tengah" },
  { value: "grobogan", label: "Kabupaten Grobogan - Jawa Tengah" },
  { value: "jepara", label: "Kabupaten Jepara - Jawa Tengah" },
  { value: "karanganyar", label: "Kabupaten Karanganyar - Jawa Tengah" },
  { value: "kendal", label: "Kabupaten Kendal - Jawa Tengah" },
  { value: "klaten", label: "Kabupaten Klaten - Jawa Tengah" },
  { value: "kudus", label: "Kabupaten Kudus - Jawa Tengah" },
  { value: "muna", label: "Kabupaten Muna - Jawa Tengah" },
  { value: "purbalingga", label: "Kabupaten Purbalingga - Jawa Tengah" },
  { value: "rembang", label: "Kabupaten Rembang - Jawa Tengah" },
  { value: "sukoharjo", label: "Kabupaten Sukoharjo - Jawa Tengah" },
  { value: "temanggung", label: "Kabupaten Temanggung - Jawa Tengah" },
  { value: "wonogiri", label: "Kabupaten Wonogiri - Jawa Tengah" },
  { value: "wonosobo", label: "Kabupaten Wonosobo - Jawa Tengah" },

  // DI Yogyakarta
  { value: "yogyakarta", label: "Kota Yogyakarta - DI Yogyakarta" },
  { value: "sleman", label: "Kabupaten Sleman - DI Yogyakarta" },
  { value: "bantul", label: "Kabupaten Bantul - DI Yogyakarta" },
  { value: "gunungkidul", label: "Kabupaten Gunungkidul - DI Yogyakarta" },
  { value: "kulon-progo", label: "Kabupaten Kulon Progo - DI Yogyakarta" },

  // Jawa Timur
  { value: "surabaya", label: "Kota Surabaya - Jawa Timur" },
  { value: "malang", label: "Kota Malang - Jawa Timur" },
  { value: "malang-kab", label: "Kabupaten Malang - Jawa Timur" },
  { value: "madura", label: "Kabupaten Madura - Jawa Timur" },
  { value: "kediri", label: "Kota Kediri - Jawa Timur" },
  { value: "kediri-kab", label: "Kabupaten Kediri - Jawa Timur" },
  { value: "blitar", label: "Kota Blitar - Jawa Timur" },
  { value: "blitar-kab", label: "Kabupaten Blitar - Jawa Timur" },
  { value: "batu", label: "Kota Batu - Jawa Timur" },
  { value: "mojokerto", label: "Kota Mojokerto - Jawa Timur" },
  { value: "mojokerto-kab", label: "Kabupaten Mojokerto - Jawa Timur" },
  { value: "pasuruan", label: "Kota Pasuruan - Jawa Timur" },
  { value: "pasuruan-kab", label: "Kabupaten Pasuruan - Jawa Timur" },
  { value: "probolinggo", label: "Kota Probolinggo - Jawa Timur" },
  { value: "probolinggo-kab", label: "Kabupaten Probolinggo - Jawa Timur" },
  { value: "bojonegoro", label: "Kabupaten Bojonegoro - Jawa Timur" },
  { value: "gresik", label: "Kabupaten Gresik - Jawa Timur" },
  { value: "jombang", label: "Kabupaten Jombang - Jawa Timur" },
  { value: "lamongan", label: "Kabupaten Lamongan - Jawa Timur" },
  { value: "lumajang", label: "Kabupaten Lumajang - Jawa Timur" },
  { value: "nganjuk", label: "Kabupaten Nganjuk - Jawa Timur" },
  { value: "ngawi", label: "Kabupaten Ngawi - Jawa Timur" },
  { value: "ponorogo", label: "Kabupaten Ponorogo - Jawa Timur" },
  { value: "pacitan", label: "Kabupaten Pacitan - Jawa Timur" },
  { value: "sampang", label: "Kabupaten Sampang - Jawa Timur" },
  { value: "situbondo", label: "Kabupaten Situbondo - Jawa Timur" },
  { value: "trenggalek", label: "Kabupaten Trenggalek - Jawa Timur" },
  { value: "tuban", label: "Kabupaten Tuban - Jawa Timur" },

  // Bali
  { value: "denpasar", label: "Kota Denpasar - Bali" },
  { value: "badung", label: "Kabupaten Badung - Bali" },
  { value: "bangli", label: "Kabupaten Bangli - Bali" },
  { value: "buleleng", label: "Kabupaten Buleleng - Bali" },
  { value: "gianyar", label: "Kabupaten Gianyar - Bali" },
  { value: "jembrana", label: "Kabupaten Jembrana - Bali" },
  { value: "karangasem", label: "Kabupaten Karangasem - Bali" },
  { value: "klungkung", label: "Kabupaten Klungkung - Bali" },

  // Nusa Tenggara Barat
  { value: "mataram", label: "Kota Mataram - Nusa Tenggara Barat" },
  { value: "bima", label: "Kota Bima - Nusa Tenggara Barat" },
  { value: "bima-kab", label: "Kabupaten Bima - Nusa Tenggara Barat" },
  { value: "lombok-utara", label: "Kabupaten Lombok Utara - Nusa Tenggara Barat" },
  { value: "lombok-barat", label: "Kabupaten Lombok Barat - Nusa Tenggara Barat" },
  { value: "lombok-tengah", label: "Kabupaten Lombok Tengah - Nusa Tenggara Barat" },
  { value: "lombok-timur", label: "Kabupaten Lombok Timur - Nusa Tenggara Barat" },
  { value: "sumbawa", label: "Kabupaten Sumbawa - Nusa Tenggara Barat" },
  { value: "sumbawa-barat", label: "Kabupaten Sumbawa Barat - Nusa Tenggara Barat" },

  // Nusa Tenggara Timur
  { value: "kupang", label: "Kota Kupang - Nusa Tenggara Timur" },
  { value: "kupang-kab", label: "Kabupaten Kupang - Nusa Tenggara Timur" },
  { value: "flores-timur", label: "Kabupaten Flores Timur - Nusa Tenggara Timur" },
  { value: "lembata", label: "Kabupaten Lembata - Nusa Tenggara Timur" },
  { value: "sikka", label: "Kabupaten Sikka - Nusa Tenggara Timur" },
  { value: "Ende", label: "Kabupaten Ende - Nusa Tenggara Timur" },
  { value: "ngada", label: "Kabupaten Ngada - Nusa Tenggara Timur" },
  { value: "manggarai", label: "Kabupaten Manggarai - Nusa Tenggara Timur" },
  { value: "manggarai-barat", label: "Kabupaten Manggarai Barat - Nusa Tenggara Timur" },
  { value: "manggarai-timur", label: "Kabupaten Manggarai Timur - Nusa Tenggara Timur" },
  { value: "rote-ndao", label: "Kabupaten Rote Ndao - Nusa Tenggara Timur" },
  { value: "sabu-raijua", label: "Kabupaten Sabu Raijua - Nusa Tenggara Timur" },
  { value: "sumba-barat", label: "Kabupaten Sumba Barat - Nusa Tenggara Timur" },
  { value: "sumba-barat-daya", label: "Kabupaten Sumba Barat Daya - Nusa Tenggara Timur" },
  { value: "sumba-timur", label: "Kabupaten Sumba Timur - Nusa Tenggara Timur" },
  { value: "sumba-tengah", label: "Kabupaten Sumba Tengah - Nusa Tenggara Timur" },
  { value: "timor-tengah-selatan", label: "Kabupaten Timor Tengah Selatan - Nusa Tenggara Timur" },
  { value: "timor-tengah-utara", label: "Kabupaten Timor Tengah Utara - Nusa Tenggara Timur" },
  { value: "timor-leste", label: "Kabupaten Timor Leste - Nusa Tenggara Timur" },

  // Kalimantan Barat
  { value: "pontianak", label: "Kota Pontianak - Kalimantan Barat" },
  { value: "singkawang", label: "Kota Singkawang - Kalimantan Barat" },
  { value: "sambas", label: "Kabupaten Sambas - Kalimantan Barat" },
  { value: "bengkayang", label: "Kabupaten Bengkayang - Kalimantan Barat" },
  { value: "kubu-raya", label: "Kabupaten Kubu Raya - Kalimantan Barat" },
  { value: "landak", label: "Kabupaten Landak - Kalimantan Barat" },
  { value: "mempawah", label: "Kabupaten Mempawah - Kalimantan Barat" },
  { value: "sanggau", label: "Kabupaten Sanggau - Kalimantan Barat" },
  { value: "sekadau", label: "Kabupaten Sekadau - Kalimantan Barat" },
  { value: "sintang", label: "Kabupaten Sintang - Kalimantan Barat" },

  // Kalimantan Tengah
  { value: "palangkaraya", label: "Kota Palangkaraya - Kalimantan Tengah" },
  { value: "kapuas", label: "Kabupaten Kapuas - Kalimantan Tengah" },
  { value: "barito-utara", label: "Kabupaten Barito Utara - Kalimantan Tengah" },
  { value: "barito-selatan", label: "Kabupaten Barito Selatan - Kalimantan Tengah" },
  { value: "barito-timur", label: "Kabupaten Barito Timur - Kalimantan Tengah" },
  { value: "gunung-mas", label: "Kabupaten Gunung Mas - Kalimantan Tengah" },
  { value: "kotawaringin-barat", label: "Kabupaten Kotawaringin Barat - Kalimantan Tengah" },
  { value: "kotawaringin-timur", label: "Kabupaten Kotawaringin Timur - Kalimantan Tengah" },
  { value: "lamandau", label: "Kabupaten Lamandau - Kalimantan Tengah" },
  { value: "murung-raya", label: "Kabupaten Murung Raya - Kalimantan Tengah" },
  { value: "pulang-pisau", label: "Kabupaten Pulang Pisau - Kalimantan Tengah" },
  { value: "sukamara", label: "Kabupaten Sukamara - Kalimantan Tengah" },
  { value: "seruyan", label: "Kabupaten Seruyan - Kalimantan Tengah" },

  // Kalimantan Selatan
  { value: "banjarmasin", label: "Kota Banjarmasin - Kalimantan Selatan" },
  { value: "banjarbaru", label: "Kota Banjarbaru - Kalimantan Selatan" },
  { value: "banjar", label: "Kabupaten Banjar - Kalimantan Selatan" },
  { value: "barito-kuala", label: "Kabupaten Barito Kuala - Kalimantan Selatan" },
  { value: "hulu-sungai-selatan", label: "Kabupaten Hulu Sungai Selatan - Kalimantan Selatan" },
  { value: "hulu-sungai-tengah", label: "Kabupaten Hulu Sungai Tengah - Kalimantan Selatan" },
  { value: "hulu-sungai-utara", label: "Kabupaten Hulu Sungai Utara - Kalimantan Selatan" },
  { value: "kapuas-kuala", label: "Kabupaten Kapuas Kuala - Kalimantan Selatan" },
  { value: "tabalong", label: "Kabupaten Tabalong - Kalimantan Selatan" },
  { value: "tanah-bumbu", label: "Kabupaten Tanah Bumbu - Kalimantan Selatan" },
  { value: "tanah-laut", label: "Kabupaten Tanah Laut - Kalimantan Selatan" },

  // Kalimantan Timur
  { value: "samarinda", label: "Kota Samarinda - Kalimantan Timur" },
  { value: "balikpapan", label: "Kota Balikpapan - Kalimantan Timur" },
  { value: "bontang", label: "Kota Bontang - Kalimantan Timur" },
  { value: "berau", label: "Kabupaten Berau - Kalimantan Timur" },
  { value: "kutai-barat", label: "Kabupaten Kutai Barat - Kalimantan Timur" },
  { value: "kutai-kartanegara", label: "Kabupaten Kutai Kartanegara - Kalimantan Timur" },
  { value: "kutai-timur", label: "Kabupaten Kutai Timur - Kalimantan Timur" },
  { value: "paser", label: "Kabupaten Paser - Kalimantan Timur" },
  { value: "penajam-paser-utara", label: "Kabupaten Penajam Paser Utara - Kalimantan Timur" },

  // Kalimantan Utara
  { value: "tarakan", label: "Kota Tarakan - Kalimantan Utara" },
  { value: "bulungan", label: "Kabupaten Bulungan - Kalimantan Utara" },
  { value: "malinau", label: "Kabupaten Malinau - Kalimantan Utara" },
  { value: "nunukan", label: "Kabupaten Nunukan - Kalimantan Utara" },
  { value: "tana-tidung", label: "Kabupaten Tana Tidung - Kalimantan Utara" },

  // Sulawesi Utara
  { value: "manado", label: "Kota Manado - Sulawesi Utara" },
  { value: "bitung", label: "Kota Bitung - Sulawesi Utara" },
  { value: "tomohon", label: "Kota Tomohon - Sulawesi Utara" },
  { value: "minahasa", label: "Kabupaten Minahasa - Sulawesi Utara" },
  { value: "minahasa-selatan", label: "Kabupaten Minahasa Selatan - Sulawesi Utara" },
  { value: "minahasa-utara", label: "Kabupaten Minahasa Utara - Sulawesi Utara" },
  { value: "minahasa-tenggara", label: "Kabupaten Minahasa Tenggara - Sulawesi Utara" },
  { value: "bolaang-mongondow", label: "Kabupaten Bolaang Mongondow - Sulawesi Utara" },
  { value: "bolaang-mongondow-selatan", label: "Kabupaten Bolaang Mongondow Selatan - Sulawesi Utara" },
  { value: "bolaang-mongondow-timur", label: "Kabupaten Bolaang Mongondow Timur - Sulawesi Utara" },
  { value: "bolaang-mongondow-utara", label: "Kabupaten Bolaang Mongondow Utara - Sulawesi Utara" },
  { value: "kepulauan-sangihe", label: "Kabupaten Kepulauan Sangihe - Sulawesi Utara" },
  { value: "kepulauan-talaud", label: "Kabupaten Kepulauan Talaud - Sulawesi Utara" },

  // Sulawesi Tengah
  { value: "palu", label: "Kota Palu - Sulawesi Tengah" },
  { value: "banggai", label: "Kabupaten Banggai - Sulawesi Tengah" },
  { value: "banggai-kepulauan", label: "Kabupaten Banggai Kepulauan - Sulawesi Tengah" },
  { value: "banggai-laut", label: "Kabupaten Banggai Laut - Sulawesi Tengah" },
  { value: "buol", label: "Kabupaten Buol - Sulawesi Tengah" },
  { value: "donggala", label: "Kabupaten Donggala - Sulawesi Tengah" },
  { value: "morowali", label: "Kabupaten Morowali - Sulawesi Tengah" },
  { value: "morowali-utara", label: "Kabupaten Morowali Utara - Sulawesi Tengah" },
  { value: "parigi-moutong", label: "Kabupaten Parigi Moutong - Sulawesi Tengah" },
  { value: "poso", label: "Kabupaten Poso - Sulawesi Tengah" },
  { value: "sigi", label: "Kabupaten Sigi - Sulawesi Tengah" },
  { value: "tojo-una-una", label: "Kabupaten Tojo Una-Una - Sulawesi Tengah" },
  { value: "toli-toli", label: "Kabupaten Toli-Toli - Sulawesi Tengah" },

  // Sulawesi Selatan
  { value: "makassar", label: "Kota Makassar - Sulawesi Selatan" },
  { value: "palopo", label: "Kota Palopo - Sulawesi Selatan" },
  { value: "parepare", label: "Kota Parepare - Sulawesi Selatan" },
  { value: "bantaeng", label: "Kabupaten Bantaeng - Sulawesi Selatan" },
  { value: "barru", label: "Kabupaten Barru - Sulawesi Selatan" },
  { value: "bone", label: "Kabupaten Bone - Sulawesi Selatan" },
  { value: "bulukumba", label: "Kabupaten Bulukumba - Sulawesi Selatan" },
  { value: "enrekang", label: "Kabupaten Enrekang - Sulawesi Selatan" },
  { value: "gowa", label: "Kabupaten Gowa - Sulawesi Selatan" },
  { value: "jeneponto", label: "Kabupaten Jeneponto - Sulawesi Selatan" },
  { value: "kepulauan-selayar", label: "Kabupaten Kepulauan Selayar - Sulawesi Selatan" },
  { value: "luwu", label: "Kabupaten Luwu - Sulawesi Selatan" },
  { value: "luwu-timur", label: "Kabupaten Luwu Timur - Sulawesi Selatan" },
  { value: "luwu-utara", label: "Kabupaten Luwu Utara - Sulawesi Selatan" },
  { value: "maros", label: "Kabupaten Maros - Sulawesi Selatan" },
  { value: "pangkajene-kepulauan", label: "Kabupaten Pangkajene Kepulauan - Sulawesi Selatan" },
  { value: "pinrang", label: "Kabupaten Pinrang - Sulawesi Selatan" },
  { value: "sidenreng-rappang", label: "Kabupaten Sidenreng Rappang - Sulawesi Selatan" },
  { value: "sinjai", label: "Kabupaten Sinjai - Sulawesi Selatan" },
  { value: "soppeng", label: "Kabupaten Soppeng - Sulawesi Selatan" },
  { value: "takalar", label: "Kabupaten Takalar - Sulawesi Selatan" },
  { value: "tana-toraja", label: "Kabupaten Tana Toraja - Sulawesi Selatan" },
  { value: "toraja-utara", label: "Kabupaten Toraja Utara - Sulawesi Selatan" },
  { value: "wajo", label: "Kabupaten Wajo - Sulawesi Selatan" },

  // Sulawesi Tenggara
  { value: "kendari", label: "Kota Kendari - Sulawesi Tenggara" },
  { value: "bau-bau", label: "Kota Bau-Bau - Sulawesi Tenggara" },
  { value: "bombana", label: "Kabupaten Bombana - Sulawesi Tenggara" },
  { value: "buton", label: "Kabupaten Buton - Sulawesi Tenggara" },
  { value: "buton-utara", label: "Kabupaten Buton Utara - Sulawesi Tenggara" },
  { value: "buton-tengah", label: "Kabupaten Buton Tengah - Sulawesi Tenggara" },
  { value: "kolaka", label: "Kabupaten Kolaka - Sulawesi Tenggara" },
  { value: "kolaka-timur", label: "Kabupaten Kolaka Timur - Sulawesi Tenggara" },
  { value: "kolaka-utara", label: "Kabupaten Kolaka Utara - Sulawesi Tenggara" },
  { value: "konawe", label: "Kabupaten Konawe - Sulawesi Tenggara" },
  { value: "konawe-kepulauan", label: "Kabupaten Konawe Kepulauan - Sulawesi Tenggara" },
  { value: "konawe-selatan", label: "Kabupaten Konawe Selatan - Sulawesi Tenggara" },
  { value: "konawe-utara", label: "Kabupaten Konawe Utara - Sulawesi Tenggara" },
  { value: "muna", label: "Kabupaten Muna - Sulawesi Tenggara" },
  { value: "muna-barat", label: "Kabupaten Muna Barat - Sulawesi Tenggara" },
  { value: "wakatobi", label: "Kabupaten Wakatobi - Sulawesi Tenggara" },

  // Maluku
  { value: "ambon", label: "Kota Ambon - Maluku" },
  { value: "tual", label: "Kota Tual - Maluku" },
  { value: "buru", label: "Kabupaten Buru - Maluku" },
  { value: "buru-selatan", label: "Kabupaten Buru Selatan - Maluku" },
  { value: "kepulauan-aru", label: "Kabupaten Kepulauan Aru - Maluku" },
  { value: "kepulauan-tanimbar", label: "Kabupaten Kepulauan Tanimbar - Maluku" },
  { value: "maluku-barat-daya", label: "Kabupaten Maluku Barat Daya - Maluku" },
  { value: "maluku-tengah", label: "Kabupaten Maluku Tengah - Maluku" },
  { value: "maluku-tenggara", label: "Kabupaten Maluku Tenggara - Maluku" },
  { value: "maluku-tenggara-barat", label: "Kabupaten Maluku Tenggara Barat - Maluku" },
  { value: "seram-bagian-barat", label: "Kabupaten Seram Bagian Barat - Maluku" },
  { value: "seram-bagian-timur", label: "Kabupaten Seram Bagian Timur - Maluku" },

  // Maluku Utara
  { value: "ternate", label: "Kota Ternate - Maluku Utara" },
  { value: "tidore", label: "Kota Tidore - Maluku Utara" },
  { value: "sofifi", label: "Kota Sofifi - Maluku Utara" },
  { value: "halmahera-barat", label: "Kabupaten Halmahera Barat - Maluku Utara" },
  { value: "halmahera-selatan", label: "Kabupaten Halmahera Selatan - Maluku Utara" },
  { value: "halmahera-tengah", label: "Kabupaten Halmahera Tengah - Maluku Utara" },
  { value: "halmahera-timur", label: "Kabupaten Halmahera Timur - Maluku Utara" },
  { value: "halmahera-utara", label: "Kabupaten Halmahera Utara - Maluku Utara" },
  { value: "kepulauan-morotai", label: "Kabupaten Kepulauan Morotai - Maluku Utara" },

  // Papua Barat
  { value: "manokwari", label: "Kota Manokwari - Papua Barat" },
  { value: "sorong", label: "Kota Sorong - Papua Barat" },
  { value: "sorong-selatan", label: "Kabupaten Sorong Selatan - Papua Barat" },
  { value: "teluk-bintuni", label: "Kabupaten Teluk Bintuni - Papua Barat" },
  { value: "teluk-wondama", label: "Kabupaten Teluk Wondama - Papua Barat" },
  { value: "fakfak", label: "Kabupaten Fakfak - Papua Barat" },
  { value: "kaimana", label: "Kabupaten Kaimana - Papua Barat" },
  { value: "manokwari-selatan", label: "Kabupaten Manokwari Selatan - Papua Barat" },
  { value: "maybrat", label: "Kabupaten Maybrat - Papua Barat" },
  { value: "pegunungan-arfak", label: "Kabupaten Pegunungan Arfak - Papua Barat" },
  { value: "raja-ampat", label: "Kabupaten Raja Ampat - Papua Barat" },

  // Papua
  { value: "jayapura", label: "Kota Jayapura - Papua" },
  { value: "asmat", label: "Kabupaten Asmat - Papua" },
  { value: "biak-numfor", label: "Kabupaten Biak Numfor - Papua" },
  { value: "boven-digoel", label: "Kabupaten Boven Digoel - Papua" },
  { value: "deiyai", label: "Kabupaten Deiyai - Papua" },
  { value: "dogiyai", label: "Kabupaten Dogiyai - Papua" },
  { value: "intan-jaya", label: "Kabupaten Intan Jaya - Papua" },
  { value: "jayawijaya", label: "Kabupaten Jayawijaya - Papua" },
  { value: "jayapura-kab", label: "Kabupaten Jayapura - Papua" },
  { value: "keerom", label: "Kabupaten Keerom - Papua" },
  { value: "kepulauan-yapen", label: "Kabupaten Kepulauan Yapen - Papua" },
  { value: "lanny-jaya", label: "Kabupaten Lanny Jaya - Papua" },
  { value: "mamberamo-raya", label: "Kabupaten Mamberamo Raya - Papua" },
  { value: "mamberamo-tengah", label: "Kabupaten Mamberamo Tengah - Papua" },
  { value: "mappi", label: "Kabupaten Mappi - Papua" },
  { value: "merauke", label: "Kabupaten Merauke - Papua" },
  { value: "mindiptana", label: "Kabupaten Mindiptana - Papua" },
  { value: "nabire", label: "Kabupaten Nabire - Papua" },
  { value: "nduga", label: "Kabupaten Nduga - Papua" },
  { value: "paniai", label: "Kabupaten Paniai - Papua" },
  { value: "pegunungan-bintang", label: "Kabupaten Pegunungan Bintang - Papua" },
  { value: "puncak", label: "Kabupaten Puncak - Papua" },
  { value: "puncak-jaya", label: "Kabupaten Puncak Jaya - Papua" },
  { value: "sarmi", label: "Kabupaten Sarmi - Papua" },
  { value: "supiori", label: "Kabupaten Supiori - Papua" },
  { value: "tolikara", label: "Kabupaten Tolikara - Papua" },
  { value: "trenggalek", label: "Kabupaten Trenggalek - Papua" },
  { value: "waropen", label: "Kabupaten Waropen - Papua" },
  { value: "yahukimo", label: "Kabupaten Yahukimo - Papua" },
  { value: "yalimo", label: "Kabupaten Yalimo - Papua" },

  // Papua Selatan
  { value: "merauke-south", label: "Kabupaten Merauke - Papua Selatan" },
  { value: "boven-digoel-south", label: "Kabupaten Boven Digoel - Papua Selatan" },
  { value: "mappi-south", label: "Kabupaten Mappi - Papua Selatan" },

  // Papua Tengah
  { value: "mimika", label: "Kabupaten Mimika - Papua Tengah" },
  { value: "puncak-tengah", label: "Kabupaten Puncak Tengah - Papua Tengah" },

  // Lampung
  { value: "bandar-lampung", label: "Kota Bandar Lampung - Lampung" },
  { value: "metro", label: "Kota Metro - Lampung" },
  { value: "lampung-barat", label: "Kabupaten Lampung Barat - Lampung" },
  { value: "lampung-selatan", label: "Kabupaten Lampung Selatan - Lampung" },
  { value: "lampung-tengah", label: "Kabupaten Lampung Tengah - Lampung" },
  { value: "lampung-timur", label: "Kabupaten Lampung Timur - Lampung" },
  { value: "lampung-utara", label: "Kabupaten Lampung Utara - Lampung" },
  { value: "pesawaran", label: "Kabupaten Pesawaran - Lampung" },
  { value: "pringsewu", label: "Kabupaten Pringsewu - Lampung" },
  { value: "tanggamus", label: "Kabupaten Tanggamus - Lampung" },
  { value: "tulang-bawang", label: "Kabupaten Tulang Bawang - Lampung" },
  { value: "tulang-bawang-barat", label: "Kabupaten Tulang Bawang Barat - Lampung" },
  { value: "way-kanan", label: "Kabupaten Way Kanan - Lampung" },

  // Riau
  { value: "pekanbaru", label: "Kota Pekanbaru - Riau" },
  { value: "dumai", label: "Kota Dumai - Riau" },
  { value: "bengkalis", label: "Kabupaten Bengkalis - Riau" },
  { value: "indragiri-hilir", label: "Kabupaten Indragiri Hilir - Riau" },
  { value: "indragiri-hulu", label: "Kabupaten Indragiri Hulu - Riau" },
  { value: "kampar", label: "Kabupaten Kampar - Riau" },
  { value: "kuantan-singingi", label: "Kabupaten Kuantan Singingi - Riau" },
  { value: "kepulauan-meranti", label: "Kabupaten Kepulauan Meranti - Riau" },
  { value: "pelalawan", label: "Kabupaten Pelalawan - Riau" },
  { value: "rokan-hilir", label: "Kabupaten Rokan Hilir - Riau" },
  { value: "rokan-hulu", label: "Kabupaten Rokan Hulu - Riau" },
  { value: "siak", label: "Kabupaten Siak - Riau" },

  // Jambi
  { value: "jambi", label: "Kota Jambi - Jambi" },
  { value: "sungai-penuh", label: "Kota Sungai Penuh - Jambi" },
  { value: "batanghari", label: "Kabupaten Batanghari - Jambi" },
  { value: "bungo", label: "Kabupaten Bungo - Jambi" },
  { value: "kerinci", label: "Kabupaten Kerinci - Jambi" },
  { value: "merangin", label: "Kabupaten Merangin - Jambi" },
  { value: "muaro-jambi", label: "Kabupaten Muaro Jambi - Jambi" },
  { value: "sarolangun", label: "Kabupaten Sarolangun - Jambi" },
  { value: "tanjung-jabung-barat", label: "Kabupaten Tanjung Jabung Barat - Jambi" },
  { value: "tanjung-jabung-timur", label: "Kabupaten Tanjung Jabung Timur - Jambi" },
  { value: "tebo", label: "Kabupaten Tebo - Jambi" },

  // Sumatera Selatan
  { value: "palembang", label: "Kota Palembang - Sumatera Selatan" },
  { value: "prabumulih", label: "Kota Prabumulih - Sumatera Selatan" },
  { value: "lubuklinggau", label: "Kota Lubuklinggau - Sumatera Selatan" },
  { value: "bengkulu-selatan", label: "Kabupaten Bengkulu Selatan - Sumatera Selatan" },
  { value: "bengkulu-tengah", label: "Kabupaten Bengkulu Tengah - Sumatera Selatan" },
  { value: "bengkulu-utara", label: "Kabupaten Bengkulu Utara - Sumatera Selatan" },
  { value: "lahat", label: "Kabupaten Lahat - Sumatera Selatan" },
  { value: "muara-enim", label: "Kabupaten Muara Enim - Sumatera Selatan" },
  { value: "musi-banyuasin", label: "Kabupaten Musi Banyuasin - Sumatera Selatan" },
  { value: "musi-rawas", label: "Kabupaten Musi Rawas - Sumatera Selatan" },
  { value: "musi-rawas-utara", label: "Kabupaten Musi Rawas Utara - Sumatera Selatan" },
  { value: "ogan-ilir", label: "Kabupaten Ogan Ilir - Sumatera Selatan" },
  { value: "ogan-komering-ilir", label: "Kabupaten Ogan Komering Ilir - Sumatera Selatan" },
  { value: "ogan-komering-ulu", label: "Kabupaten Ogan Komering Ulu - Sumatera Selatan" },
  { value: "ogan-komering-ulu-selatan", label: "Kabupaten Ogan Komering Ulu Selatan - Sumatera Selatan" },
  { value: "ogan-komering-ulu-timur", label: "Kabupaten Ogan Komering Ulu Timur - Sumatera Selatan" },

  // Sumatera Utara
  { value: "medan", label: "Kota Medan - Sumatera Utara" },
  { value: "binjai", label: "Kota Binjai - Sumatera Utara" },
  { value: "pematangsiantar", label: "Kota Pematangsiantar - Sumatera Utara" },
  { value: "sibolga", label: "Kota Sibolga - Sumatera Utara" },
  { value: "tanjung-balai", label: "Kota Tanjung Balai - Sumatera Utara" },
  { value: "tebing-tinggi", label: "Kota Tebing Tinggi - Sumatera Utara" },
  { value: "asahan", label: "Kabupaten Asahan - Sumatera Utara" },
  { value: "batu-bara", label: "Kabupaten Batu Bara - Sumatera Utara" },
  { value: "dairi", label: "Kabupaten Dairi - Sumatera Utara" },
  { value: "deliserdang", label: "Kabupaten Deli Serdang - Sumatera Utara" },
  { value: "humbang-hasundutan", label: "Kabupaten Humbang Hasundutan - Sumatera Utara" },
  { value: "karo", label: "Kabupaten Karo - Sumatera Utara" },
  { value: "labuhan-batu", label: "Kabupaten Labuhan Batu - Sumatera Utara" },
  { value: "labuhan-batu-selatan", label: "Kabupaten Labuhan Batu Selatan - Sumatera Utara" },
  { value: "labuhan-batu-utara", label: "Kabupaten Labuhan Batu Utara - Sumatera Utara" },
  { value: "langkat", label: "Kabupaten Langkat - Sumatera Utara" },
  { value: "mandailing-natal", label: "Kabupaten Mandailing Natal - Sumatera Utara" },
  { value: "nias", label: "Kabupaten Nias - Sumatera Utara" },
  { value: "nias-barat", label: "Kabupaten Nias Barat - Sumatera Utara" },
  { value: "nias-selatan", label: "Kabupaten Nias Selatan - Sumatera Utara" },
  { value: "nias-utara", label: "Kabupaten Nias Utara - Sumatera Utara" },
  { value: "padang-lawas", label: "Kabupaten Padang Lawas - Sumatera Utara" },
  { value: "padang-lawas-utara", label: "Kabupaten Padang Lawas Utara - Sumatera Utara" },
  { value: "pakpak-bharat", label: "Kabupaten Pakpak Bharat - Sumatera Utara" },
  { value: "samosir", label: "Kabupaten Samosir - Sumatera Utara" },
  { value: "serdang-bedagai", label: "Kabupaten Serdang Bedagai - Sumatera Utara" },
  { value: "simalungun", label: "Kabupaten Simalungun - Sumatera Utara" },
  { value: "tapanuli-selatan", label: "Kabupaten Tapanuli Selatan - Sumatera Utara" },
  { value: "tapanuli-tengah", label: "Kabupaten Tapanuli Tengah - Sumatera Utara" },
  { value: "tapanuli-utara", label: "Kabupaten Tapanuli Utara - Sumatera Utara" },
  { value: "toba-samosir", label: "Kabupaten Toba Samosir - Sumatera Utara" },
  { value: "toba", label: "Kabupaten Toba - Sumatera Utara" },

  // Sumatera Barat
  { value: "padang", label: "Kota Padang - Sumatera Barat" },
  { value: "pariaman", label: "Kota Pariaman - Sumatera Barat" },
  { value: "padangpanjang", label: "Kota Padangpanjang - Sumatera Barat" },
  { value: "payakumbuh", label: "Kota Payakumbuh - Sumatera Barat" },
  { value: "sawahlunto", label: "Kota Sawahlunto - Sumatera Barat" },
  { value: "solok", label: "Kota Solok - Sumatera Barat" },
  { value: "agam", label: "Kabupaten Agam - Sumatera Barat" },
  { value: "dharmasraya", label: "Kabupaten Dharmasraya - Sumatera Barat" },
  { value: "kepulauan-mentawai", label: "Kabupaten Kepulauan Mentawai - Sumatera Barat" },
  { value: "limapuluh-kota", label: "Kabupaten Limapuluh Kota - Sumatera Barat" },
  { value: "padang-pariaman", label: "Kabupaten Padang Pariaman - Sumatera Barat" },
  { value: "pasaman", label: "Kabupaten Pasaman - Sumatera Barat" },
  { value: "pasaman-barat", label: "Kabupaten Pasaman Barat - Sumatera Barat" },
  { value: "pesisir-selatan", label: "Kabupaten Pesisir Selatan - Sumatera Barat" },
  { value: "sijunjung", label: "Kabupaten Sijunjung - Sumatera Barat" },
  { value: "solok-selatan", label: "Kabupaten Solok Selatan - Sumatera Barat" },
  { value: "tanah-datar", label: "Kabupaten Tanah Datar - Sumatera Barat" },

  // Bengkulu
  { value: "bengkulu", label: "Kota Bengkulu - Bengkulu" },
  { value: "bengkulu-selatan", label: "Kabupaten Bengkulu Selatan - Bengkulu" },
  { value: "bengkulu-tengah", label: "Kabupaten Bengkulu Tengah - Bengkulu" },
  { value: "bengkulu-utara", label: "Kabupaten Bengkulu Utara - Bengkulu" },
  { value: "kaur", label: "Kabupaten Kaur - Bengkulu" },
  { value: "kepahiang", label: "Kabupaten Kepahiang - Bengkulu" },
  { value: "lebong", label: "Kabupaten Lebong - Bengkulu" },
  { value: "muko-muko", label: "Kabupaten Muko-Muko - Bengkulu" },
  { value: "rejang-lebong", label: "Kabupaten Rejang Lebong - Bengkulu" },
  { value: "seluma", label: "Kabupaten Seluma - Bengkulu" },

  // DI Aceh Darussalam
  // (Already covered in Aceh section above)
];
